global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ecatalog-api"
    scheme: https
    metrics_path: /metrics

    static_configs:
      - targets:
          - host.docker.internal:7069

    tls_config:
      insecure_skip_verify: true
